name: "active_leaks"
url: "https://services7.arcgis.com/2ECs938g489DMWjt/ArcGIS/rest/services/Job_Status_Public_View/FeatureServer/5/query"
type: "point"
cache_ttl_hours: 24
output_file: "active_leaks"
arrow_columns:
  - status
  - priority
parquet_columns:
  - status
  - priority
  - wonum
  - reportdate
  - wsadd_formataddress
  - type
  - comm_description
  - water_type